server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**

        - id: ms-categoria-service
          uri: lb://ms-categoria-service
          predicates:
            - Path=/categorias/**
          filters:
            - AuthFilter

        - id: ms-cliente-service
          uri: lb://ms-cliente-service
          predicates:
            - Path=/api/clientes/**
          filters:
            - AuthFilter

        - id: ms-inventario-service
          uri: lb://ms-inventario-service
          predicates:
            - Path=/api/stock/**
          filters:
            - AuthFilter

        - id: ms-producto-service
          uri: lb://ms-producto-service
          predicates:
            - Path=/productos/**

        - id: ms-venta-service
          uri: lb://ms-venta-service
          predicates:
            - Path=/api/ventas/**
          filters:
            - AuthFilter
